# Data Cleaning and Preparation Project: Used Car Sales in Germany

The goal of this project is to clean and prepare a data set containing 50,000 used car listings from "eBay Kleinanzeigen," a classifieds section of Germany's Ebay site. We'll inject some observations about the data as we go, but our primary goal is to find and fix any dirty data that will impede our ability to perform accurate statistical analysis. 

Here are some of the questions we'll task ourselves to answer, which will influence decisions regarding how we handle problematic data. We will limit our analysis to the top 10 car brands, which represent 

1. What is the average price for each car brand? Which brands are most and least expensive?
2. What is the average mileage for each brand? Does it correlate to price?
3. What are the most common brand/model combinations?
4. How does reported damage influence price?

Our data set was scraped and uploaded to Kaggle for public use. It includes 20 attributes for each listing, ranging from categorical (Vehicle Type, Gear Box, Brand) to quantitative (Kilometers, Price, Power PS).

For those who are curious, here's the full data dictionary:

- __dateCrawled__ - When this ad was first crawled. All field-values are taken from this date.
- __name__ - Name of the car.
- __seller__ - Whether the seller is private or a dealer.
- __offerType__ - The type of listing
- __price__ - The price on the ad to sell the car.
- __abtest__ - Whether the listing is included in an A/B test.
- __vehicleType__ - The vehicle Type.
- __yearOfRegistration__ - The year in which the car was first registered.
- __gearbox__ - The transmission type.
- __powerPS__ - The power of the car in PS. This is a measure of engine power, sometimes referred to as 'metric horsepower'.
- __model__ - The car model name.
- __kilometer__ - How many kilometers the car has driven.
- __monthOfRegistration__ - The month in which the car was first registered.
- __fuelType__ - What type of fuel the car uses.
- __brand__ - The brand of the car.
- __notRepairedDamage__ - If the car has a damage which is not yet repaired.
- __dateCreated__ - The date on which the eBay listing was created.
- __nrOfPictures__ - The number of pictures in the ad.
- __postalCode__ - The postal code for the location of the vehicle.
- __lastSeenOnline__ - When the crawler saw this ad last online.

### Getting Familiar with Our Data

We'll begin by importing the data set along with the libraries we'll need:

In [2]:
import numpy as np
import pandas as pd
pd.set_option('mode.chained_assignment', None)
autos = pd.read_csv('autos.csv', encoding='Latin-1')

And print a sample of the data table to have an initial look at the values:

In [3]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

Let's check out some more information about our table:

In [4]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

A few initial observations:

1) It looks like the values in many of our numerical columns are in string format (e.g. "price"). We'll have to convert those to int or float and strip out any non-numerical characters (e.g. dollar signs).

2) Five columns contain missing (null) values: "vehicleType", "gearbox", "model", "fuelType", and "notRepairedDamage". We'll need to investigate these individually and decide if it's best to remove, replace or leave as is.

3) Several columns contain German text (e.g. "seller"). We should convert those to English.

4) The column names are in camelcase and should be converted to snakecase.

### Cleaning Up Our Data

Let's start with our last observation in the previous section: the column names should be reformatted to snakecase. As a reminder, here are all the column names:

In [5]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

Converting to snakecase means we need to separate each word with an underscore character. We should also convert all characters to lowercase:

In [6]:
corrected_columns = {'dateCrawled':'date_crawled', 
                 'name':'name',
                 'seller':'seller',
                 'offerType':'offer_type',
                 'price':'price',
                 'abtest':'ab_test',
                 'vehicleType':'vehicle_type',
                 'yearOfRegistration':'registration_year',
                 'gearbox':'gearbox',
                 'powerPS':'power_ps',
                 'model':'model',
                 'odometer':'odometer',
                 'monthOfRegistration':'registration_month',
                 'fuelType':'fuel_type',
                 'brand':'brand',
                 'notRepairedDamage':'unrepaired_damage',
                 'dateCreated':'ad_created',
                 'nrOfPictures':'nr_of_pictures',
                 'postalCode':'postal_code',
                 'lastSeen':'last_seen'}

new_columns = pd.Series(autos.columns).map(corrected_columns) 
autos.columns = new_columns

Let's make sure our column names were successfully updated:

In [7]:
autos.head()

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Looks good. Let's keep exploring the data to see what else needs to be cleaned, starting with some basic stats:

In [8]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-21 16:37:21,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

Based on top value frequency, we can see a couple columns for which over 99% of values are identical: 

- "seller" is mostly "privat", or "private" in English
- "offer_type" is mostly "Angebot", which appears to translate to "bid". This would make sense given that we're looking at data from Ebay.

We'll drop these as they aren't providing any useful insight:

In [9]:
autos = autos.drop(columns=["seller","offer_type"])
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

Continuing to analyze our data table, we can see that something strange is going on with the "nr_of_pictures" column: it's showing 0 for all summary stats. Does this column contain only zeroes? Looking back at the table sample we generated earlier, it does appear that's likely the case. Let's see:

In [10]:
autos["nr_of_pictures"].value_counts()

0    50000
Name: nr_of_pictures, dtype: int64

As suspected, every value in the "nr_of_pictures" column is 0. Perhaps the scrape failed to pick up this data. Let's go ahead and drop this column as well:

In [11]:
autos = autos.drop(columns=["nr_of_pictures"])
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

We can spot a handful of other anomalies in the remaining columns:

1. "name" is showing a suspiciously high number of unique values (~38,000). That suggests little to no standardization in the naming convention. Compare that to the "model" column, which is showing only 245 unique values.
2. Some of the min and max values seem off:
    - For "registration_year", the min value is 1000 and the max value is 9999. Those years make no sense.
    - For "power_ps", min is 0 and max is 17,700. Both of these are impossible.
    - For "registration_month", min value is 0, but the only values that map to a month are 1 - 12.
3. Earlier we had spotted some numerical columns that are formatted as strings, which is going to prevent us from applying any summary stats. We can see above that the affected columns are "price" and "odometer".
4. "postal_code" is displaying summary stats like mean and standard deviation, but since this is a nominal variable, those stats don't have any meaning. We could correct this by convering the column into a string.

Let's investigate the anomalies in 1. and 2. before executing any additonal cleanup.

### Cleaning up Names, Brands and Models

We'll generate a frequency table of the "name" column to see what the format looks like:

In [12]:
autos["name"].value_counts()

Ford_Fiesta                                                       78
BMW_316i                                                          75
Volkswagen_Golf_1.4                                               75
Volkswagen_Polo                                                   72
BMW_318i                                                          72
BMW_320i                                                          71
Opel_Corsa                                                        71
Renault_Twingo                                                    70
Volkswagen_Golf                                                   57
Opel_Corsa_1.2_16V                                                56
BMW_116i                                                          53
Opel_Corsa_B                                                      52
Peugeot_206                                                       52
Ford_Focus                                                        50
Volkswagen_Polo_1.2                                               48
Volkswagen_Golf_1.6                                               47
Opel_Astra                                                        43
Opel_Corsa_1.0_12V                                                41
Volkswagen_Passat_Variant_1.9_TDI                                 39
BMW_320d_DPF_Touring                                              38
BMW_520i                                                          37
Opel_Astra_1.6                                                    35
Audi_A4_Avant_2.0_TDI_DPF                                         34
Renault_Twingo_1.2                                                33
Ford_Mondeo                                                       32
Fiat_Punto                                                        32
Volkswagen_Golf_1.9_TDI                                           32
Ford_Ka                                                           30
Renault_Clio                                                      29
Ford_Fiesta_1.3                                                   29
                                                                  ..
CitroÃ«n_xsara_guenstig                                             1
Bmw_F20_120d                                                       1
Skoda_Octavia_1.6_Combi_Style                                      1
BMW_528i_1._Hand_Scheckheft_gepfl._Zustand_TÃœV_10/17               1
Mercedes_A140_Motorschaden                                         1
Audi_80_Coupe_Typ89_QUATTRO                                        1
BMW_335d_DPF_Touring_Aut._Edition_Lifestyle                        1
Toyota_Corolla_1.4_VVT_i                                           1
Golf_3_TDI_zu_verkaufen                                            1
HONDA_FR_V                                                         1
Volkswagen_Caddy_1.9_TDI_"the_eyecatcher"                          1
Ford_Sierra_Ghia+TOP_Ausstattung                                   1
Mercedes_Benz_SL_500_Cabrio_155000km__gt._Zustand_Garagenwagen     1
Mercedes_300E_4matic                                               1
Iveco_35_C_12_V_L_DPF_AGile_Maxi+Hoch+Lang_Zwillingsbe             1
Audi_TTS_Coupe_Einzelstueck                                        1
Toyota_MR_2__Garagenwagen__Nichtraucher__Top_Zustand               1
Polo_+_einen_Satz_Sommer_und_winterreifen                          1
Volkswagen_Scirocco__F1_Schaltung__1._Hd.__unfallfrei              1
Verkaufe_Unfallwagen!                                              1
A2_1.6Fsi_Motorschaden                                             1
VW_Polo_6N_mit_TÃœV                                                 1
Golf_2__1_6_Madison                                                1
Peugeot_106_Sport_Tuev/_Service_neu_Klima_Alufelgen                1
Nissan_Juke_dci_Tekna_Ausstattung                                  1
Gebrauchsspuren___Motor_top                                        1
Volkswagen_Passat_2.0_TDI_BlueMotion_Technology                    1
Opel_Corsa_b_1.0_TÃœV_bis_11.2017                                   1
Ford_Focus_Sportausstatung_tuev_neu_tifer_gelegt                   1
Mercedes_Benz_C_200_Diesel_schalter_2_Hand_scheckheft              1
Name: name, Length: 38754, dtype: int64

It looks like our assumption was right: these values include not just the car manufacturer, but also information about the model. Some even include very specific specs like engine capacity, chips, etc. Each piece of information is seperated by an underscore, which we might be able to use to extract and categorize some of this information. Remember, we have two other columns that provide info about the type of car we're observing: "model" and "brand". Perhaps this info is sufficient and we don't need the "name" column after all. Let's look at a sample of these three columns together to figure out the best approach:

In [13]:
autos[["name", "brand", "model"]].head(20)

,name,brand,model
0,Peugeot_807_160_NAVTECH_ON_BOARD,peugeot,andere
1,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,bmw,7er
2,Volkswagen_Golf_1.6_United,volkswagen,golf
3,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,smart,fortwo
4,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,ford,focus
5,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,chrysler,voyager
6,VW_Golf_III_GT_Special_Electronic_Green_Metall...,volkswagen,golf
7,Golf_IV_1.9_TDI_90PS,volkswagen,golf
8,Seat_Arosa,seat,arosa
9,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,renault,megane
10,VW_Golf_Tuning_in_siber/grau,volkswagen,NaN
11,Mercedes_A140_Motorschaden,mercedes_benz,NaN
12,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,smart,fortwo
13,Audi_A3_1.6_tuning,audi,a3
14,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,renault,clio
15,Corvette_C3_Coupe_T_Top_Crossfire_Injection,sonstige_autos,NaN
16,Opel_Vectra_B_Kombi,opel,vectra
17,Volkswagen_Scirocco_2_G60,volkswagen,scirocco
18,Verkaufen_mein_bmw_e36_320_i_touring,bmw,3er
19,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,mazda,andere

One issue we spotted earlier is that there are ~3,000 entries that are missing "model" data. Perhaps we can extract that info from the "name" column to help fill those holes (luckily there are no missing values in the "brand" column). It may be a challenge, though, due to the messy nature of the "name" entries; info on model seems to start after the first underscore, but some entries have the information spread out across multiple words (each separated by underscores), or the model info starts on the third word. 

Let's take a closer look at the entries with missing "model" values:

In [14]:
autos.loc[autos["model"].isnull(),["name","brand","model"]]

                                                    name           brand model
10                          VW_Golf_Tuning_in_siber/grau      volkswagen   NaN
11                            Mercedes_A140_Motorschaden   mercedes_benz   NaN
15           Corvette_C3_Coupe_T_Top_Crossfire_Injection  sonstige_autos   NaN
23      Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima         peugeot   NaN
25     Ford_escort_kombi_an_bastler_mit_ghia_ausstattung            ford   NaN
27                Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE            ford   NaN
41     Passat_3b_1.9_TDI_Highline__angemeldet_mit_tuv...      volkswagen   NaN
46                                          BMW_mit__Lpg             bmw   NaN
60                                 VW_Vento_1_8_Tuev_NEU      volkswagen   NaN
71     Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...            opel   NaN
92                                          Zu_verkaufen             bmw   NaN
140             Ssangyong_Actyon_SUV_2.0_xdi2wd_55000_km  sonstige_autos   NaN
152                                  Ssanyong_Rexton_2.7  sonstige_autos   NaN
175                                            MG_MGB_GT  sonstige_autos   NaN
186                                        Audi_A_4_grau            audi   NaN
193                           SEHR_GEPFLEGTER_FIAT_STILO            fiat   NaN
196                Bmw_316i_lpg_coupe___Tausch_moeglich_             bmw   NaN
236                    Mercedes_Benz_E_320_4_Matic_Kombi   mercedes_benz   NaN
259                        guenstiges_Auto_/_auch_defekt  sonstige_autos   NaN
276                Peugeot_106_1_4_55kw_Nuer_heute!!!!!!         peugeot   NaN
281                                      Opel_vectra_1.8            opel   NaN
283                              3_Fahrzeug_zu_Verkaufen  sonstige_autos   NaN
296                        Dodge_Nitro_4.0_Automatik_R/T  sonstige_autos   NaN
301                           Kaufe_alle_Autos_bietet_an  sonstige_autos   NaN
320                           Peugeot_206_viele_Neuteile         peugeot   NaN
324                                 Ford_Focus_abzugeben            ford   NaN
359                                           Proton_PKW  sonstige_autos   NaN
389                                      Vw_polo_classic      volkswagen   NaN
392                            Trabant_601_L_mit_Papiere         trabant   NaN
435                               Ford_Puma_zu_verkaufen            ford   NaN
...                                                  ...             ...   ...
49482                                    SUV_Kia_Sorento             kia   NaN
49496                                        Bmw_e39_520             bmw   NaN
49522               Mazda_Demio_zu_verkaufen!_RESERVIERT           mazda   NaN
49531                           Fiat_Merena_Diesel_Kombi            fiat   NaN
49551        Golf_IV_an_Bastler_zuverkaufen__reserviert_      volkswagen   NaN
49574                               OPEL_ASTRA_AUTOMATIC            opel   NaN
49585                  Mercedes_Benz_A140!_Super_Zustand   mercedes_benz   NaN
49605  Seat_Arosa_1_0_mit_Klimaanlage_Servolenkung_Hu_Au            seat   NaN
49612         Opel_Corsa_1.2_Schiebedach_Voll_fahrbereit  sonstige_autos   NaN
49617  VW_Golf_7_Cup_Edition_Sport_DSG_mit_Schaltwipp...      volkswagen   NaN
49679      An_Bastler_Volvo_V40_Kombi_1.8_Liter_Benziner           volvo   NaN
49689                                      VW_GOLF_V_1.9      volkswagen   NaN
49691                         Smart_Fortwo_Cabrio_diesel           smart   NaN
49720                                          MG_Andere  sonstige_autos   NaN
49741                                   Verkaufe_Ford_Ka            ford   NaN
49745                                         ALPINA_B12  sonstige_autos   NaN
49750                                 Volkswagen_Polo_6n      volkswagen   NaN
49758                             Opel_astra_1_6_eco_tec            opel   NaN
49773                              320d_springt_nicht_an             bmw   NaN
49844                                Fahrzeug_Ankauf!!!!            opel   NaN
49876                             Audi_a5_3.0_tdi_s_line            audi   NaN
49892                                         Vw_T_4_Bus      volkswagen   NaN
49926                                     Vw_golf_cabrio      volkswagen   NaN
49932               Mercedes_320_cdi_7_Sitzer_Avantgarde   mercedes_benz   NaN
49941                   Maserati_Ghibli_Diesel_Automatik  sonstige_autos   NaN
49950         Volvo_V70_2_II__2002__AHK__Klima__Volleder           volvo   NaN
49954                                328_Cabrio_Schalter             bmw   NaN
49984  Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...  sonstige_autos   NaN
49985                          Verkaufe_meinen_vw_vento!      volkswagen   NaN
49993           Audi_A3__1_8l__Silber;_schoenes_Fahrzeug            audi   NaN

[2758 rows x 3 columns]

Let's also look at the "brand" frequency for rows with missing "model" values to see if that helps us spot any trends or solutions:

In [15]:
autos.loc[autos["model"].isnull(),["name","brand","model"]]["brand"].value_counts()

sonstige_autos    546
volkswagen        489
bmw               267
opel              240
ford              163
mercedes_benz     156
audi              154
peugeot           110
renault            88
fiat               69
mazda              50
smart              39
hyundai            37
citroen            35
seat               33
nissan             28
honda              26
mitsubishi         25
chevrolet          21
skoda              21
kia                20
toyota             19
alfa_romeo         18
volvo              17
chrysler           12
trabant            12
suzuki             11
subaru              9
rover               6
jeep                6
porsche             6
daewoo              6
saab                3
daihatsu            3
lancia              3
dacia               3
jaguar              2
lada                2
mini                2
land_rover          1
Name: brand, dtype: int64

I'll be honest, I thought "sonstige_autos" was a foreign car brand. Google tells me it's actually German for "other cars". Yikes. Moving along...let's see what the "name" column looks like for just this subset of "other cars":

In [16]:
autos.loc[(autos["model"].isnull()) & (autos["brand"] == "sonstige_autos"),["name","brand","model"]]

                                                    name           brand model
15           Corvette_C3_Coupe_T_Top_Crossfire_Injection  sonstige_autos   NaN
140             Ssangyong_Actyon_SUV_2.0_xdi2wd_55000_km  sonstige_autos   NaN
152                                  Ssanyong_Rexton_2.7  sonstige_autos   NaN
175                                            MG_MGB_GT  sonstige_autos   NaN
259                        guenstiges_Auto_/_auch_defekt  sonstige_autos   NaN
283                              3_Fahrzeug_zu_Verkaufen  sonstige_autos   NaN
296                        Dodge_Nitro_4.0_Automatik_R/T  sonstige_autos   NaN
301                           Kaufe_alle_Autos_bietet_an  sonstige_autos   NaN
359                                           Proton_PKW  sonstige_autos   NaN
461                              Gut_erhaltene_Alufelgen  sonstige_autos   NaN
486                                         Wartburg_1.3  sonstige_autos   NaN
625                          Werkaufen_meine_Iveco_deily  sonstige_autos   NaN
658                                     Pontiac_Firebird  sonstige_autos   NaN
826                       Ich_suche_dring._neues_Auto...  sonstige_autos   NaN
888                              Cadillac_SRX_3.6_V6_AWD  sonstige_autos   NaN
1081         Pontiac_Firebird_3.4___org._30.000_km___LPG  sonstige_autos   NaN
1102        Pontiac_Firebird_2_8L_V6_Targa__Tuev_07/2016  sonstige_autos   NaN
1179   Andere_russ._LuAZ_967M_Schwimmwagen_NVA_GSSD_a...  sonstige_autos   NaN
1360                                       Buick_Riviera  sonstige_autos   NaN
1393                                        Wartburg_353  sonstige_autos   NaN
1524        Dodge__RAM_Laramie_1500_V8_HEMI_Crew_Cab_AHK  sonstige_autos   NaN
1548                1936_Daimler_Fifteen_Special_Projekt  sonstige_autos   NaN
1620   Dodge_RAM_B300_Mowag_Mowag_Dodge_V8_selten_Neu...  sonstige_autos   NaN
1763                                    DKW_1000_S_Coupe  sonstige_autos   NaN
1798                       VW_SHARAN_TDI_1.9_TOP_ZUSTAND  sonstige_autos   NaN
1862                                         MG_MGF_1.8i  sonstige_autos   NaN
1866   MICROCAR_M.GO_Dynamic_Mopedauto_Leichtkraftfah...  sonstige_autos   NaN
1894                                    Cadillac_Deville  sonstige_autos   NaN
1932   Verkaufe_unser_Wohnmobilbegleitfahrzeug_mit_Tr...  sonstige_autos   NaN
2051                                      Wartburg_353_W  sonstige_autos   NaN
...                                                  ...             ...   ...
47362                                   Cadillac_Deville  sonstige_autos   NaN
47406                                Tesla_Model_S_85_KW  sonstige_autos   NaN
47444                            Suche_Auto_bis_250_Euro  sonstige_autos   NaN
47445             1969er_Dodge_D200_Pickup_Autom._383cui  sonstige_autos   NaN
47537                                       Wartburg_1.3  sonstige_autos   NaN
47634                                        Ferrari_FXX  sonstige_autos   NaN
47792       Cadillac_STS_4.6__V8_Luxury_Sport_EU_Version  sonstige_autos   NaN
47821                                       Iveco_Andere  sonstige_autos   NaN
47908                             Auto_bis_1000Â€_gesucht  sonstige_autos   NaN
48195                                 Sang_Yong_mercedes  sonstige_autos   NaN
48221                  Triumph_TR_7_Cabrio_H_Kennzeichen  sonstige_autos   NaN
48287                                Suche_Kleinwagen!!!  sonstige_autos   NaN
48818  Caterham_Lotus_Super_Seven_Linkslenker_mit_gru...  sonstige_autos   NaN
48882                                         SUCHE_AUTO  sonstige_autos   NaN
48932                                   Triumph_Spitfire  sonstige_autos   NaN
48946  Unfallwagen_Motorschaden_Getriebeschaden_Ankau...  sonstige_autos   NaN
48960    Aixam_City_Premium__LEDER__45km/h__ab_16_Jahren  sonstige_autos   NaN
48962                                       Triumph_TR3A  sonstige_autos   NaN
49037                        Ssangyong_Rexton_RX_270_Xdi  sonstige_autos   NaN
49085    Dodge_Unfall_Viper_SRT_10_mit_8.4_Liter__650_PS  sonstige_autos   NaN
49139                       Dodge_Dakota_3.9l_magnum_lpg  sonstige_autos   NaN
49237                              Aixam_scouty_r_cabrio  sonstige_autos   NaN
49270                      WARTBURG_311_//__Baujahr_1960  sonstige_autos   NaN
49271                                        Corvette_C6  sonstige_autos   NaN
49391  Lamborghini_Gallardo_LP560_4_E_Gear_"Callisto_...  sonstige_autos   NaN
49612         Opel_Corsa_1.2_Schiebedach_Voll_fahrbereit  sonstige_autos   NaN
49720                                          MG_Andere  sonstige_autos   NaN
49745                                         ALPINA_B12  sonstige_autos   NaN
49941                   Maserati_Ghibli_Diesel_Automatik  sonstige_autos   NaN
49984  Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...  sonstige_autos   NaN

[546 rows x 3 columns]

The more entries we look at, the tougher this challenge appears to be. For now I don't think it's wise to dedicate the resources required to fill in the missing model information. Perhaps an improvement for a later date. For the time being we will leave these columns as is and focus our analysis on the more complete "brand column". We'll come back to that later.

Next we'll explore our max and min value issues, starting with "registration_year":

### Investigating Max and Min Anomalies

In [17]:
autos["registration_year"].value_counts().sort_index()

1000       1
1001       1
1111       1
1500       1
1800       2
1910       9
1927       1
1929       1
1931       1
1934       2
1937       4
1938       1
1939       1
1941       2
1943       1
1948       1
1950       3
1951       2
1952       1
1953       1
1954       2
1955       2
1956       5
1957       2
1958       4
1959       7
1960      34
1961       6
1962       4
1963       9
        ...
2001    2703
2002    2533
2003    2727
2004    2737
2005    3015
2006    2708
2007    2304
2008    2231
2009    2098
2010    1597
2011    1634
2012    1323
2013     806
2014     666
2015     399
2016    1316
2017    1453
2018     492
2019       3
2800       1
4100       1
4500       1
4800       1
5000       4
5911       1
6200       1
8888       1
9000       2
9996       1
9999       4
Name: registration_year, Length: 97, dtype: int64

Luckily not many of these values look off. According to Wikipedia the first German cars were registered in 1906, so the handful of entries predating that year should be fixed. 

Similarily, some rows list years that are beyond when the scrape occured (2016). That's impossible, of course, so these rows are incorrect.

Let's use a range between 1910 and 2016. How many rows fall outside of that range?

In [18]:
autos.loc[(autos["registration_year"] < 1910) | (autos["registration_year"] > 2016),["registration_year"]]["registration_year"].count() / autos["registration_year"].count() * 100

3.9440000000000004

Just under 4% of listings. That's not a massive subset of our data, but do we really need to remove it? This column isn't integral in answering any immediate questions, so I feel it's better to keep the records and change anything outside our bounds to NaN. That way we keep more data in the columns we're interested in, while still being able to see summary stats for our "registration_year" column (as Python will simply ignore the NaN values).

In [19]:
autos.loc[(autos["registration_year"] < 1910) | (autos["registration_year"] > 2016),["registration_year"]] = np.nan
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004.0,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997.0,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009.0,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007.0,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003.0,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006.0,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995.0,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998.0,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000.0,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997.0,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,NaN,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000.0,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010.0,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999.0,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007.0,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982.0,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999.0,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990.0,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995.0,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004.0,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003.0,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004.0,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015.0,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010.0,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014.0,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996.0,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992.0,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005.0,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007.0,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004.0,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010.0,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001.0,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004.0,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004.0,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983.0,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012.0,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992.0,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003.0,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996.0,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011.0,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995.0,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998.0,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004.0,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999.0,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000.0,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995.0,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010.0,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013.0,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001.0,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997.0,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012.0,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016.0,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009.0,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997.0,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001.0,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011.0,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996.0,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014.0,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013.0,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996.0,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

Let's look at the distribution of this column now that the problematic rows have been corrected:

In [20]:
reg_year_distr = autos["registration_year"].value_counts(normalize=True).sort_values(ascending=False) * 100
reg_year_distr

2000.0    6.983426
2005.0    6.277588
1999.0    6.246356
2004.0    5.698759
2003.0    5.677938
2006.0    5.638378
2001.0    5.627967
2002.0    5.274007
1998.0    5.107437
2007.0    4.797202
2008.0    4.645207
2009.0    4.368285
1997.0    4.222537
2011.0    3.402182
2010.0    3.325144
1996.0    3.006579
2012.0    2.754643
2016.0    2.740068
1995.0    2.733822
2013.0    1.678188
2014.0    1.386691
1994.0    1.374198
1993.0    0.926543
2015.0    0.830765
1990.0    0.822437
1992.0    0.814108
1991.0    0.741234
1989.0    0.376863
1988.0    0.295661
1985.0    0.218622
            ...
1977.0    0.045807
1966.0    0.045807
1975.0    0.039560
1969.0    0.039560
1965.0    0.035396
1964.0    0.024985
1910.0    0.018739
1963.0    0.018739
1959.0    0.014575
1961.0    0.012493
1956.0    0.010411
1962.0    0.008328
1958.0    0.008328
1937.0    0.008328
1950.0    0.006246
1934.0    0.004164
1941.0    0.004164
1951.0    0.004164
1954.0    0.004164
1955.0    0.004164
1957.0    0.004164
1943.0    0.002082
1931.0    0.002082
1938.0    0.002082
1939.0    0.002082
1929.0    0.002082
1948.0    0.002082
1953.0    0.002082
1952.0    0.002082
1927.0    0.002082
Name: registration_year, Length: 78, dtype: float64

It looks like the year with the greatest number of registrations was 2000. In fact, the largest percentages appear to be years that fall within the 21st century. Let's see what their combined share is:

In [21]:
reg_year_distr = reg_year_distr.loc[range(2000,2007)]
reg_year_distr.sum()

41.17806279670192

We can see that a whopping 41% of cars were registered after the year 2000.

Next up, let's look more closely at the "power_ps" column:

In [22]:
autos["power_ps"].value_counts().sort_index()

0        5500
1           5
2           2
3           3
4           4
5          13
6           3
8           2
9           1
10          3
11          4
12          1
14          1
15          5
16          1
18          6
19          3
20          4
21          1
23          4
24          1
25          2
26         39
27          5
29          5
30          3
32          2
33          9
34         27
35          2
         ...
1704        1
1753        1
1771        1
1779        1
1780        1
1781        1
1793        1
1796        1
1800        3
1986        1
1988        1
1998        2
2018        1
2729        1
3500        1
3750        1
4400        1
5867        1
6045        1
6226        1
6512        1
7511        1
8404        1
9011        1
14009       1
15001       1
15016       1
16011       1
16312       1
17700       1
Name: power_ps, Length: 448, dtype: int64

PS and horsepower are virtually interchangeable as their unit values map almost 1:1. So what's a reasonable low point for PS? A bit of research shows that some older cars had less than 10 horsepower! So we shouldn't be so quick to discard our values on the extreme low end. It _is_ impossible, though, to have 0 horsepower, and we can see that 5,500 entries have a value of 0 PS. These will need to be fixed.

On the flip side, some of the values on the high end are clearly way too high, reaching a max of 17,700 PS! For context, the fastest production cars today are around 1400 PS.

Let's see how many entries are above 1400 PS:

In [23]:
autos.loc[autos["power_ps"] > 1400,"power_ps"].count()

35

So a very small number of entries -- about 35 -- have a PS value that is likely too high.

Because the PS column isn't aiding in answering any of our key questions, and we have over 5,000 entries with incorrect values, it doesn't make sense to remove these rows. Let's instead convert anything outside our range to NaN values:

In [24]:
autos.loc[(autos["power_ps"] > 1400) | (autos["power_ps"] < 1),['power_ps']] = np.nan
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004.0,manuell,158.0,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997.0,automatik,286.0,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009.0,manuell,102.0,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007.0,automatik,71.0,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003.0,manuell,NaN,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006.0,automatik,150.0,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995.0,manuell,90.0,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998.0,manuell,90.0,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000.0,manuell,NaN,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997.0,manuell,90.0,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,NaN,manuell,90.0,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000.0,NaN,NaN,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010.0,automatik,71.0,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999.0,manuell,101.0,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007.0,manuell,75.0,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982.0,automatik,203.0,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999.0,manuell,101.0,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990.0,manuell,205.0,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995.0,manuell,150.0,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004.0,manuell,124.0,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003.0,manuell,131.0,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004.0,manuell,320.0,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015.0,manuell,184.0,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010.0,manuell,120.0,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014.0,automatik,306.0,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996.0,manuell,116.0,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992.0,manuell,54.0,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005.0,NaN,NaN,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007.0,manuell,110.0,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004.0,automatik,204.0,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010.0,automatik,136.0,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001.0,manuell,50.0,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004.0,automatik,150.0,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004.0,manuell,163.0,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983.0,manuell,70.0,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012.0,automatik,88.0,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992.0,automatik,150.0,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003.0,manuell,116.0,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996.0,automatik,136.0,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011.0,manuell,90.0,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995.0,manuell,105.0,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998.0,manuell,115.0,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004.0,manuell,NaN,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999.0,manuell,101.0,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000.0,NaN,NaN,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995.0,automatik,NaN,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010.0,automatik,218.0,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013.0,manuell,150.0,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001.0,manuell,231.0,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997.0,manuell,NaN,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012.0,manuell,156.0,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016.0,manuell,NaN,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009.0,manuell,120.0,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997.0,manuell,NaN,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001.0,automatik,299.0,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011.0,automatik,239.0,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996.0,manuell,75.0,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014.0,automatik,69.0,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013.0,manuell,150.0,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996.0,manuell,101.0,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

Finally, let's take a closer look at how many values in "registration_month" are 0:

In [25]:
autos["registration_month"].value_counts().sort_index()

0     5075
1     3282
2     3008
3     5071
4     4102
5     4107
6     4368
7     3949
8     3191
9     3389
10    3651
11    3360
12    3447
Name: registration_month, dtype: int64

Just over 5,000 values have an invalid month listed and will need to be corrected.

Once again, this column isn't terribly useful in answering any of our original questions about the data set, and there are over 5,000 rows affected, so we'll simply convert any 0 values to NaN:F

In [26]:
autos.loc[(autos["registration_month"] == 0),["registration_month"]] = np.nan
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004.0,manuell,158.0,andere,"150,000km",3.0,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997.0,automatik,286.0,7er,"150,000km",6.0,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009.0,manuell,102.0,golf,"70,000km",7.0,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007.0,automatik,71.0,fortwo,"70,000km",6.0,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003.0,manuell,NaN,focus,"150,000km",7.0,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006.0,automatik,150.0,voyager,"150,000km",4.0,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995.0,manuell,90.0,golf,"150,000km",8.0,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998.0,manuell,90.0,golf,"150,000km",12.0,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000.0,manuell,NaN,arosa,"150,000km",10.0,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997.0,manuell,90.0,megane,"150,000km",7.0,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,NaN,manuell,90.0,NaN,"150,000km",4.0,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000.0,NaN,NaN,NaN,"150,000km",NaN,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010.0,automatik,71.0,fortwo,"50,000km",9.0,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999.0,manuell,101.0,a3,"150,000km",11.0,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007.0,manuell,75.0,clio,"150,000km",9.0,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982.0,automatik,203.0,NaN,"80,000km",6.0,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999.0,manuell,101.0,vectra,"150,000km",5.0,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990.0,manuell,205.0,scirocco,"150,000km",6.0,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995.0,manuell,150.0,3er,"150,000km",NaN,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004.0,manuell,124.0,andere,"150,000km",2.0,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003.0,manuell,131.0,a4,"150,000km",5.0,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004.0,manuell,320.0,911,"150,000km",4.0,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015.0,manuell,184.0,cooper,"10,000km",1.0,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010.0,manuell,120.0,NaN,"150,000km",2.0,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014.0,automatik,306.0,5er,"30,000km",12.0,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996.0,manuell,116.0,NaN,"150,000km",4.0,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992.0,manuell,54.0,polo,"125,000km",2.0,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005.0,NaN,NaN,NaN,"150,000km",NaN,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007.0,manuell,110.0,cooper,"150,000km",7.0,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004.0,automatik,204.0,e_klasse,"150,000km",10.0,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010.0,automatik,136.0,c4,"60,000km",4.0,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001.0,manuell,50.0,lupo,"150,000km",4.0,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004.0,automatik,150.0,vito,"150,000km",10.0,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004.0,manuell,163.0,slk,"150,000km",11.0,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983.0,manuell,70.0,golf,"150,000km",2.0,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012.0,automatik,88.0,jazz,"100,000km",11.0,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992.0,automatik,150.0,80,"150,000km",12.0,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003.0,manuell,116.0,c_klasse,"150,000km",2.0,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996.0,automatik,136.0,e_klasse,"150,000km",9.0,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011.0,manuell,90.0,polo,"70,000km",11.0,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995.0,manuell,105.0,escort,"125,000km",3.0,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998.0,manuell,115.0,astra,"150,000km",12.0,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004.0,manuell,NaN,fabia,"90,000km",7.0,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999.0,manuell,101.0,focus,"150,000km",4.0,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000.0,NaN,NaN,NaN,"150,000km",NaN,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995.0,automatik,NaN,NaN,"150,000km",NaN,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010.0,automatik,218.0,300c,"125,000km",11.0,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013.0,manuell,150.0,a3,"50,000km",11.0,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001.0,manuell,231.0,3er,"150,000km",10.0,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997.0,manuell,NaN,polo,"150,000km",5.0,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012.0,manuell,156.0,a_klasse,"30,000km",12.0,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016.0,manuell,NaN,twingo,"150,000km",NaN,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009.0,manuell,120.0,andere,"125,000km",9.0,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997.0,manuell,NaN,NaN,"150,000km",7.0,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001.0,automatik,299.0,a6,"150,000km",1.0,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011.0,automatik,239.0,q5,"100,000km",1.0,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996.0,manuell,75.0,astra,"150,000km",5.0,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014.0,automatik,69.0,500,"5,000km",11.0,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013.0,manuell,150.0,a3,"40,000km",11.0,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996.0,manuell,101.0,vectra,"150,000km",1.0,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

Next we'll need to convert our two numerical categories that are currently formatted as strings - "price" and "odometer":

In [27]:
autos["price"] = autos["price"].str.replace('$','').str.replace(',','').astype(int)
autos["price"]

0         5000
1         8500
2         8990
3         4350
4         1350
5         7900
6          300
7         1990
8          250
9          590
10         999
11         350
12        5299
13        1350
14        3999
15       18900
16         350
17        5500
18         300
19        4150
20        3500
21       41500
22       25450
23        7999
24       48500
25          90
26         777
27           0
28        5250
29        4999
         ...
49970    15800
49971      950
49972     3300
49973     6000
49974        0
49975     9700
49976     5900
49977     5500
49978      900
49979    11000
49980      400
49981     2000
49982     1950
49983      600
49984        0
49985     1000
49986    15900
49987    21990
49988     9550
49989      150
49990    17500
49991      500
49992     4800
49993     1650
49994     5000
49995    24900
49996     1980
49997    13200
49998    22900
49999     1250
Name: price, Length: 50000, dtype: int64

In [28]:
autos["odometer"] = autos["odometer"].str.replace('km','').str.replace(',','').astype(int)
autos["odometer"]

0        150000
1        150000
2         70000
3         70000
4        150000
5        150000
6        150000
7        150000
8        150000
9        150000
10       150000
11       150000
12        50000
13       150000
14       150000
15        80000
16       150000
17       150000
18       150000
19       150000
20       150000
21       150000
22        10000
23       150000
24        30000
25       150000
26       125000
27       150000
28       150000
29       150000
          ...
49970     60000
49971    150000
49972    150000
49973    150000
49974    150000
49975    100000
49976    150000
49977    150000
49978    150000
49979     70000
49980    125000
49981    150000
49982     90000
49983    150000
49984    150000
49985    150000
49986    125000
49987     50000
49988    150000
49989    150000
49990     30000
49991    150000
49992    125000
49993    150000
49994    150000
49995    100000
49996    150000
49997      5000
49998     40000
49999    150000
Name: odometer, Length: 50000, dtype: int64

We should rename our odometer column so we remember that the values are referencing km:

In [29]:
autos.columns = autos.rename(columns={'odometer':'odometer_km'}).columns
autos.columns

Index(['date_crawled', 'name', 'price', 'ab_test', 'vehicle_type',
       'registration_year', 'gearbox', 'power_ps', 'model', 'odometer_km',
       'registration_month', 'fuel_type', 'brand', 'unrepaired_damage',
       'ad_created', 'postal_code', 'last_seen'],
      dtype='object')

Done! And now that these two columns have been converted to integers, we should be able to see their summary stats and detect any anomalies, just as we've done for the other columns. Remember that we already know from a previous step that there are 2,357 unique values in this column:

In [30]:
autos["price"].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

The first problem we can see is that the minimum value is 0, meaning we have at least one listing with no price. Likewise, the max value is $100,000,000, which seems like a _bit_ of a stretch for a used car. That's likely an error.

Let's take a closer look:

In [31]:
autos["price"].value_counts().sort_index()

0           1421
1            156
2              3
3              1
5              2
8              1
9              1
10             7
11             2
12             3
13             2
14             1
15             2
17             3
18             1
20             4
25             5
29             1
30             7
35             1
40             6
45             4
47             1
49             4
50            49
55             2
59             1
60             9
65             5
66             1
            ...
151990         1
155000         1
163500         1
163991         1
169000         1
169999         1
175000         1
180000         1
190000         1
194000         1
197000         1
198000         1
220000         1
250000         1
259000         1
265000         1
295000         1
299000         1
345000         1
350000         1
999990         1
999999         2
1234566        1
1300000        1
3890000        1
10000000       1
11111111       2
12345678       3
27322222       1
99999999       1
Name: price, Length: 2357, dtype: int64

We can see that 1,421 entries have a price of \\$0. We know this can't be correct as eBay doesn't allow you to list free items, so we should feel comfortable removing these entries from our set. We can surmise that anything with a price of $1 or higher could be correct as a starting bid tactic, so we'll keep those.

On the opposite end, we can see some outrageously high prices. We can see a jump from \\$350,000 to almost \$1,000,000, which seems like a good cut-off point. Many of the values above that are obviously meaningless (e.g. \$999,999; \$11,111,111; and \$99,999,999). Let's remove the entries above \$350,000:

In [32]:
autos = autos[autos["price"].between(1,35000)]
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004.0,manuell,158.0,andere,150000,3.0,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997.0,automatik,286.0,7er,150000,6.0,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990,test,limousine,2009.0,manuell,102.0,golf,70000,7.0,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007.0,automatik,71.0,fortwo,70000,6.0,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003.0,manuell,NaN,focus,150000,7.0,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006.0,automatik,150.0,voyager,150000,4.0,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995.0,manuell,90.0,golf,150000,8.0,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998.0,manuell,90.0,golf,150000,12.0,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,250,test,NaN,2000.0,manuell,NaN,arosa,150000,10.0,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997.0,manuell,90.0,megane,150000,7.0,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,999,test,NaN,NaN,manuell,90.0,NaN,150000,4.0,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,350,control,NaN,2000.0,NaN,NaN,NaN,150000,NaN,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010.0,automatik,71.0,fortwo,50000,9.0,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,1350,control,limousine,1999.0,manuell,101.0,a3,150000,11.0,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007.0,manuell,75.0,clio,150000,9.0,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982.0,automatik,203.0,NaN,80000,6.0,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,350,test,kombi,1999.0,manuell,101.0,vectra,150000,5.0,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990.0,manuell,205.0,scirocco,150000,6.0,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995.0,manuell,150.0,3er,150000,NaN,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004.0,manuell,124.0,andere,150000,2.0,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003.0,manuell,131.0,a4,150000,5.0,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015.0,manuell,184.0,cooper,10000,1.0,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010.0,manuell,120.0,NaN,150000,2.0,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996.0,manuell,116.0,NaN,150000,4.0,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,777,control,kleinwagen,1992.0,manuell,54.0,polo,125000,2.0,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
28,2016-03-19 21:56:19,MINI_Cooper_D,5250,control,kleinwagen,2007.0,manuell,110.0,cooper,150000,7.0,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004.0,automatik,204.0,e_klasse,150000,10.0,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002.0,manuell,60.0,2_reihe,150000,6.0,benzin,peugeot,ja,2016-03-14 00:00:00,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002.0,automatik,218.0,c_klasse,150000,7.0,benzin,mercedes_benz,nein,2016-03-14 00:00:00,41065,2016-03-16 07:19:04
32,2016-03-20 05:03:03,Corsa_mit_TÃœV_5.2016,350,control,kleinwagen,1999.0,manuell,NaN,corsa,150000,7.0,benzin,opel,NaN,2016-03-20 00:00:00,27619,2016-04-06 03:15:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986.0,automatik,90.0,andere,150000,9.0,diesel,mercedes_benz,nein,2016-04-01 00:00:00,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005.0,manuell,136.0,x_trail,150000,5.0,diesel,nissan,nein,2016-03-17 00:00:00,17379,2016-03-25 23:18:15
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010.0,automatik,136.0,c4,60000,4.0,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,950,test,kleinwagen,2001.0,manuell,50.0,lupo,150000,4.0,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004.0,automatik,150.0,vito,150000,10.0,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004.0,manuell,163.0,slk,150000,11.0,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012.0,automatik,88.0,jazz,100000,11.0,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992.0,automatik,150.0,80,150000,12.0,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003.0,manuell,116.0,c_klasse,150000,2.0,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,900,control,limousine,1996.0,automatik,136.0,e_klasse,150000,9.0,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011.0,manuell,90.0,polo,70000,11.0,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,400,control,kombi,1995.0,manuell,105.0,escort,125000,3.0,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998.0,manuell,115.0,astra,150000,12.0,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004.0,manuell,NaN,fabia,90000,7.0,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,600,test,kleinwagen,1999.0,manuell,101.0,focus,150000,4.0,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995.0,automatik,NaN,NaN,150000,NaN,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010.0,automatik,218.0,300c,125000,11.0,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013.0,manuell,150.0,a3,50000,11.0,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,9550,control,coupe,2001.0,manuell,231.0,3er,150000,10.0,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997.0,manuell,NaN,polo,150000,5.0,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012.0,manuell,156.0,a_klasse,30000,12.0,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,500,control,NaN,2016.0,manuell,NaN,twingo,150000,NaN,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009.0,manuell,120.0,andere,125000,9.0,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997.0,manuell,NaN,NaN,150000,7.0,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001.0,automatik,299.0,a6,150000,1.0,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011.0,automatik,239.0,q5,100000,1.0,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996.0,manuell,75.0,astra,150000,5.0,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014.0,automatik,69.0,500,5000,11.0,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013.0,manuell,150.0,a3,40000,11.0,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,1250,control,limousine,1996.0,manuell,101.0,vectra,150000,1.0,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

Now that our outliers are gone, let's take another look at the summary stats for this column:

In [33]:
autos["price"].describe()

count    48056.000000
mean      5331.427168
std       6047.229364
min          1.000000
25%       1200.000000
50%       2999.000000
75%       7200.000000
max      35000.000000
Name: price, dtype: float64

Notice that the mean price of a used car on eBay Kleinanzeigenis is just under \\$6,000. This is notably higher than our median (listed above as 50th percentile), which is $3,000, suggesting that we have a significant percentage of high-price listings that are skewing our average price upwards. The standard deviation and quartiles appears to support that.

Let's do the same analysis of our "odometer_km" column:

In [34]:
autos["odometer_km"].describe()

count     48056.000000
mean     126488.263692
std       39140.930914
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

Something looks off with the way this data is skewed. Why are the 50% and 75% the same? Also, the 75% is equivalent to the max value? Let's look at the number of unique values:

In [35]:
autos["odometer_km"].unique().shape

(13,)

Hmm. Only 13 unique values. Let's look at what those are and their frequency:

In [36]:
autos["odometer_km"].value_counts().sort_index()

5000        803
10000       221
20000       693
30000       725
40000       766
50000       963
60000      1112
70000      1185
80000      1390
90000      1710
100000     2089
125000     5025
150000    31374
Name: odometer_km, dtype: int64

Now it's clear. This column buckets data, and over 50% of our entries have fallen into the 150,000KM bucket. That explains why our mean is so high, and why our percentiles are skewed so aggressively to the high end of our range. This seems to make sense - used cars are typically older and have endured significant mileage.

There are no obvious outliers that should be removed from this data set, so we won't drop any rows.

### Cleaning the Date Columns

We have five columns that contain date information:

- "date_crawled"
- "last_seen"
- "ad_created"
- "registration_month"
- "registration_year"

Let's look at our info summary to see how these columns are currently formatted:

In [37]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48056 entries, 0 to 49999
Data columns (total 17 columns):
date_crawled          48056 non-null object
name                  48056 non-null object
price                 48056 non-null int64
ab_test               48056 non-null object
vehicle_type          43483 non-null object
registration_year     46179 non-null float64
gearbox               45728 non-null object
power_ps              43059 non-null float64
model                 45630 non-null object
odometer_km           48056 non-null int64
registration_month    43586 non-null float64
fuel_type             44047 non-null object
brand                 48056 non-null object
unrepaired_damage     38985 non-null object
ad_created            48056 non-null object
postal_code           48056 non-null int64
last_seen             48056 non-null object
dtypes: float64(3), int64(3), object(11)
memory usage: 6.6+ MB

"registration_month" and "registration_year" are both formatted as integers. The remaining columns, which were all collected through our scraping tool, are formatted as strings. We'll need to convert these if we want to be able to take any quantitative measurements. Luckily, all three columns follow the same format, where the first ten digits represent year, month and date. Let's extract those digits, convert to an integer and look at the distribution of each of these columns, starting with "date_crawled".

In [38]:
autos["date_crawled"] = autos["date_crawled"].str[:10].str.replace("-","").astype(int)
date_crawled_distr = autos["date_crawled"].value_counts(normalize=True, dropna=False).sort_index().multiply(100)
date_crawled_distr

20160305    2.536624
20160306    1.406692
20160307    3.608290
20160308    3.337773
20160309    3.314883
20160310    3.223323
20160311    3.248294
20160312    3.708174
20160313    1.569003
20160314    3.660313
20160315    3.429332
20160316    2.965290
20160317    3.162977
20160318    1.286000
20160319    3.468870
20160320    3.787248
20160321    3.714417
20160322    3.291993
20160323    3.223323
20160324    2.927834
20160325    3.152572
20160326    3.237889
20160327    3.104711
20160328    3.479274
20160329    3.418928
20160330    3.375229
20160331    3.177543
20160401    3.360663
20160402    3.543782
20160403    3.868404
20160404    3.658232
20160405    1.292242
20160406    0.318379
20160407    0.141502
Name: date_crawled, dtype: float64

We can see the crawl occured for about a month, between 2016-03-05 and 2016-04-07. The distribution is fairly even.

Next we'll look at "ad_created":

In [39]:
autos["ad_created"] = autos["ad_created"].str[:10].str.replace("-","").astype(int)
ad_created_distr = autos["ad_created"].value_counts(normalize=True, dropna=False).sort_index().multiply(100)
ad_created_distr

20150810    0.002081
20150909    0.002081
20151110    0.002081
20151205    0.002081
20151230    0.002081
20160103    0.002081
20160107    0.002081
20160110    0.004162
20160113    0.002081
20160114    0.002081
20160116    0.002081
20160122    0.002081
20160127    0.006243
20160129    0.002081
20160201    0.002081
20160202    0.004162
20160205    0.004162
20160207    0.002081
20160208    0.002081
20160209    0.002081
20160211    0.002081
20160212    0.004162
20160214    0.004162
20160216    0.002081
20160217    0.002081
20160218    0.004162
20160219    0.006243
20160220    0.004162
20160221    0.006243
20160222    0.002081
              ...
20160309    3.323206
20160310    3.192109
20160311    3.283669
20160312    3.691527
20160313    1.702181
20160314    3.520892
20160315    3.406442
20160316    3.017313
20160317    3.123439
20160318    1.356750
20160319    3.360663
20160320    3.793491
20160321    3.731064
20160322    3.277426
20160323    3.208756
20160324    2.921591
20160325    3.167138
20160326    3.242051
20160327    3.094307
20160328    3.493841
20160329    3.410604
20160330    3.356501
20160331    3.183786
20160401    3.360663
20160402    3.510488
20160403    3.891293
20160404    3.697769
20160405    1.163226
20160406    0.326702
20160407    0.126935
Name: ad_created, Length: 75, dtype: float64

Ads were created between 2015-08-10 and 2016-04-07. It appears that most ads were created towards the latter end of our range. Let's see what percentage of ads were created within the most recent 1/4 of our range:

In [40]:
ad_created_distr_post2000 = ad_created_distr.iloc[(73//4) * -1:,]
ad_created_distr_post2000.sum()

52.16414183452638

Wow, more than half! Perhaps our sample set caught the site in a key inflection point of user growth. Very interesting.

Finally we'll look at "last_seen":

In [41]:
autos["last_seen"] = autos["last_seen"].str[:10].str.replace("-","").astype(int)
last_seen_distr = autos["last_seen"].value_counts(normalize=True, dropna=False).sort_index().multiply(100)
last_seen_distr

20160305     0.108207
20160306     0.436990
20160307     0.538955
20160308     0.749126
20160309     0.965540
20160310     1.075828
20160311     1.246462
20160312     2.393041
20160313     0.894789
20160314     1.263110
20160315     1.598136
20160316     1.645996
20160317     2.819627
20160318     0.734560
20160319     1.591893
20160320     2.064258
20160321     2.066339
20160322     2.147495
20160323     1.860330
20160324     1.981022
20160325     1.926919
20160326     1.681372
20160327     1.569003
20160328     2.099634
20160329     2.247378
20160330     2.490844
20160331     2.382637
20160401     2.291077
20160402     2.501249
20160403     2.528300
20160404     2.465873
20160405    12.400117
20160406    22.134593
20160407    13.099301
Name: last_seen, dtype: float64

We don't have any information about how quickly our crawler is able to comb through these listings, but it makes sense that more than 50% of "last seen" dates would be in the final three days our crawler was active. If the crawler is able to traverse all listings in a single day, then it would be interesting to note that, say, 22% of listings were last seen on the second to last day (were all of those completed sales?). We would need more information to glean anything meaningful.

### Translating German to English

Let's move on to translating German words to English to make our data easier to understand. We'll look at the current state of our dataframe to see what needs to be translated.

In [42]:
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,20160326,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004.0,manuell,158.0,andere,150000,3.0,lpg,peugeot,nein,20160326,79588,20160406
1,20160404,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997.0,automatik,286.0,7er,150000,6.0,benzin,bmw,nein,20160404,71034,20160406
2,20160326,Volkswagen_Golf_1.6_United,8990,test,limousine,2009.0,manuell,102.0,golf,70000,7.0,benzin,volkswagen,nein,20160326,35394,20160406
3,20160312,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007.0,automatik,71.0,fortwo,70000,6.0,benzin,smart,nein,20160312,33729,20160315
4,20160401,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003.0,manuell,NaN,focus,150000,7.0,benzin,ford,nein,20160401,39218,20160401
5,20160321,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006.0,automatik,150.0,voyager,150000,4.0,diesel,chrysler,NaN,20160321,22962,20160406
6,20160320,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995.0,manuell,90.0,golf,150000,8.0,benzin,volkswagen,NaN,20160320,31535,20160323
7,20160316,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998.0,manuell,90.0,golf,150000,12.0,diesel,volkswagen,nein,20160316,53474,20160407
8,20160322,Seat_Arosa,250,test,NaN,2000.0,manuell,NaN,arosa,150000,10.0,NaN,seat,nein,20160322,7426,20160326
9,20160316,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997.0,manuell,90.0,megane,150000,7.0,benzin,renault,nein,20160316,15749,20160406
10,20160315,VW_Golf_Tuning_in_siber/grau,999,test,NaN,NaN,manuell,90.0,NaN,150000,4.0,benzin,volkswagen,nein,20160314,86157,20160407
11,20160316,Mercedes_A140_Motorschaden,350,control,NaN,2000.0,NaN,NaN,NaN,150000,NaN,benzin,mercedes_benz,NaN,20160316,17498,20160316
12,20160331,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010.0,automatik,71.0,fortwo,50000,9.0,benzin,smart,nein,20160331,34590,20160406
13,20160323,Audi_A3_1.6_tuning,1350,control,limousine,1999.0,manuell,101.0,a3,150000,11.0,benzin,audi,nein,20160323,12043,20160401
14,20160323,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007.0,manuell,75.0,clio,150000,9.0,benzin,renault,NaN,20160323,81737,20160401
15,20160401,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982.0,automatik,203.0,NaN,80000,6.0,benzin,sonstige_autos,nein,20160401,61276,20160402
16,20160316,Opel_Vectra_B_Kombi,350,test,kombi,1999.0,manuell,101.0,vectra,150000,5.0,benzin,opel,nein,20160316,57299,20160318
17,20160329,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990.0,manuell,205.0,scirocco,150000,6.0,benzin,volkswagen,nein,20160329,74821,20160405
18,20160326,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995.0,manuell,150.0,3er,150000,NaN,benzin,bmw,NaN,20160326,54329,20160402
19,20160317,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004.0,manuell,124.0,andere,150000,2.0,lpg,mazda,nein,20160317,40878,20160317
20,20160305,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003.0,manuell,131.0,a4,150000,5.0,diesel,audi,NaN,20160305,53913,20160307
22,20160328,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015.0,manuell,184.0,cooper,10000,1.0,benzin,mini,nein,20160328,44789,20160401
23,20160310,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010.0,manuell,120.0,NaN,150000,2.0,diesel,peugeot,nein,20160310,30900,20160317
25,20160321,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996.0,manuell,116.0,NaN,150000,4.0,benzin,ford,ja,20160321,27574,20160401
26,20160403,Volkswagen_Polo_Fox,777,control,kleinwagen,1992.0,manuell,54.0,polo,125000,2.0,benzin,volkswagen,nein,20160403,38110,20160405
28,20160319,MINI_Cooper_D,5250,control,kleinwagen,2007.0,manuell,110.0,cooper,150000,7.0,diesel,mini,ja,20160319,15745,20160407
29,20160402,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004.0,automatik,204.0,e_klasse,150000,10.0,diesel,mercedes_benz,nein,20160402,47638,20160402
30,20160314,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002.0,manuell,60.0,2_reihe,150000,6.0,benzin,peugeot,ja,20160314,57076,20160314
31,20160314,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002.0,automatik,218.0,c_klasse,150000,7.0,benzin,mercedes_benz,nein,20160314,41065,20160316
32,20160320,Corsa_mit_TÃœV_5.2016,350,control,kleinwagen,1999.0,manuell,NaN,corsa,150000,7.0,benzin,opel,NaN,20160320,27619,20160406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,20160401,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986.0,automatik,90.0,andere,150000,9.0,diesel,mercedes_benz,nein,20160401,40227,20160405
49969,20160317,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005.0,manuell,136.0,x_trail,150000,5.0,diesel,nissan,nein,20160317,17379,20160325
49970,20160321,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010.0,automatik,136.0,c4,60000,4.0,diesel,citroen,nein,20160321,14947,20160407
49971,20160329,W.Lupo_1.0,950,test,kleinwagen,2001.0,manuell,50.0,lupo,150000,4.0,benzin,volkswagen,nein,20160329,65197,20160329
49972,20160326,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004.0,automatik,150.0,vito,150000,10.0,diesel,mercedes_benz,ja,20160326,65326,20160328
49973,20160327,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004.0,manuell,163.0,slk,150000,11.0,benzin,mercedes_benz,nein,20160327,53567,20160327
49975,20160327,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012.0,automatik,88.0,jazz,100000,11.0,hybrid,honda,nein,20160327,84385,20160405
49976,20160319,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992.0,automatik,150.0,80,150000,12.0,benzin,audi,nein,20160319,36100,20160407
49977,20160331,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003.0,manuell,116.0,c_klasse,150000,2.0,diesel,mercedes_benz,nein,20160331,33739,20160406
49978,20160404,Mercedes_Benz_E_200_Classic,900,control,limousine,1996.0,automatik,136.0,e_klasse,150000,9.0,benzin,mercedes_benz,ja,20160404,24405,20160406
49979,20160320,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011.0,manuell,90.0,polo,70000,11.0,diesel,volkswagen,nein,20160320,48455,20160407
49980,20160312,Ford_Escort_Turnier_16V,400,control,kombi,1995.0,manuell,105.0,escort,125000,3.0,benzin,ford,NaN,20160312,56218,20160406
49981,20160315,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998.0,manuell,115.0,astra,150000,12.0,benzin,opel,nein,20160315,86859,20160405
49982,20160329,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004.0,manuell,NaN,fabia,90000,7.0,benzin,skoda,NaN,20160329,45884,20160329
49983,20160306,Ford_focus_99,600,test,kleinwagen,1999.0,manuell,101.0,focus,150000,4.0,benzin,ford,NaN,20160306,52477,20160309
49985,20160402,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995.0,automatik,NaN,NaN,150000,NaN,benzin,volkswagen,NaN,20160402,30900,20160406
49986,20160404,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010.0,automatik,218.0,300c,125000,11.0,diesel,chrysler,nein,20160404,73527,20160406
49987,20160322,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013.0,manuell,150.0,a3,50000,11.0,diesel,audi,nein,20160322,94362,20160326
49988,20160328,BMW_330_Ci,9550,control,coupe,2001.0,manuell,231.0,3er,150000,10.0,benzin,bmw,nein,20160328,83646,20160407
49989,20160311,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997.0,manuell,NaN,polo,150000,5.0,benzin,volkswagen,ja,20160311,21244,20160312
49990,20160321,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012.0,manuell,156.0,a_klasse,30000,12.0,benzin,mercedes_benz,nein,20160321,58239,20160406
49991,20160306,Kleinwagen,500,control,NaN,2016.0,manuell,NaN,twingo,150000,NaN,benzin,renault,NaN,20160306,61350,20160306
49992,20160310,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009.0,manuell,120.0,andere,125000,9.0,lpg,fiat,nein,20160310,68642,20160313
49993,20160315,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997.0,manuell,NaN,NaN,150000,7.0,benzin,audi,NaN,20160315,65203,20160406
49994,20160322,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001.0,automatik,299.0,a6,150000,1.0,benzin,audi,nein,20160322,46537,20160406
49995,20160327,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011.0,automatik,239.0,q5,100000,1.0,diesel,audi,nein,20160327,82131,20160401
49996,20160328,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996.0,manuell,75.0,astra,150000,5.0,benzin,opel,nein,20160328,44807,20160402
49997,20160402,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014.0,automatik,69.0,500,5000,11.0,benzin,fiat,nein,20160402,73430,20160404
49998,20160308,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013.0,manuell,150.0,a3,40000,11.0,diesel,audi,nein,20160308,35683,20160405
49999,20160314,Opel_Vectra_1.6_16V,1250,control,limousine,1996.0,manuell,101.0,vectra,150000,1.0,benzin,opel,nein,20160313,45897,20160406

We can see some German in "vehicle_type". Let's generate a list of all unique values and create a dictionary with any necessary translations:

In [43]:
autos["vehicle_type"].unique()

array(['bus', 'limousine', 'kleinwagen', 'kombi', nan, 'coupe', 'suv',
       'cabrio', 'andere'], dtype=object)

In [44]:
vehicle_type_dict = {'bus': 'bus',
                     'limousine': 'limousine',
                     'kleinwagen': 'small car',
                     'kombi': 'station_wagon',
                     'cabrio': 'convertible',
                     'andere':'other'
                    }

fixed_vehicle_column = autos["vehicle_type"].map(vehicle_type_dict)
autos["vehicle_type"] = fixed_vehicle_column
autos["vehicle_type"]

0                  bus
1            limousine
2            limousine
3            small car
4        station_wagon
5                  bus
6            limousine
7            limousine
8                  NaN
9                  bus
10                 NaN
11                 NaN
12           small car
13           limousine
14           small car
15                 NaN
16       station_wagon
17                 NaN
18                 bus
19                 NaN
20       station_wagon
22         convertible
23                 bus
25       station_wagon
26           small car
28           small car
29       station_wagon
30           small car
31       station_wagon
32           small car
             ...
49968        limousine
49969              NaN
49970              bus
49971        small car
49972              bus
49973      convertible
49975        small car
49976    station_wagon
49977        limousine
49978        limousine
49979        small car
49980    station_wagon
49981    station_wagon
49982        small car
49983        small car
49985              NaN
49986        limousine
49987        limousine
49988              NaN
49989        small car
49990        limousine
49991              NaN
49992        small car
49993        small car
49994    station_wagon
49995        limousine
49996      convertible
49997      convertible
49998    station_wagon
49999        limousine
Name: vehicle_type, Length: 48056, dtype: object

Next we'll translate "gearbox", which is easy to transalte as it has only two self-explanatory values:

In [45]:
gearbox_type_dict = {'manuell':'manual',
                    'automatik': 'automatic'
                    }

fixed_gearbox_column = autos["gearbox"].map(gearbox_type_dict)
autos["gearbox"] = fixed_gearbox_column
autos["gearbox"]

0           manual
1        automatic
2           manual
3        automatic
4           manual
5        automatic
6           manual
7           manual
8           manual
9           manual
10          manual
11             NaN
12       automatic
13          manual
14          manual
15       automatic
16          manual
17          manual
18          manual
19          manual
20          manual
22          manual
23          manual
25          manual
26          manual
28          manual
29       automatic
30          manual
31       automatic
32          manual
           ...
49968    automatic
49969       manual
49970    automatic
49971       manual
49972    automatic
49973       manual
49975    automatic
49976    automatic
49977       manual
49978    automatic
49979       manual
49980       manual
49981       manual
49982       manual
49983       manual
49985    automatic
49986    automatic
49987       manual
49988       manual
49989       manual
49990       manual
49991       manual
49992       manual
49993       manual
49994    automatic
49995    automatic
49996       manual
49997    automatic
49998       manual
49999       manual
Name: gearbox, Length: 48056, dtype: object

Next is "unreparied_damage", which is another simple column with only a binary yes/no structure:

In [46]:
damage_type_dict = {'ja':'yes',
                    'nein': 'no'
                    }

fixed_damage_column = autos["unrepaired_damage"].map(damage_type_dict)
autos["unrepaired_damage"] = fixed_damage_column
autos["unrepaired_damage"]

0         no
1         no
2         no
3         no
4         no
5        NaN
6        NaN
7         no
8         no
9         no
10        no
11       NaN
12        no
13        no
14       NaN
15        no
16        no
17        no
18       NaN
19        no
20       NaN
22        no
23        no
25       yes
26        no
28       yes
29        no
30       yes
31        no
32       NaN
        ...
49968     no
49969     no
49970     no
49971     no
49972    yes
49973     no
49975     no
49976     no
49977     no
49978    yes
49979     no
49980    NaN
49981     no
49982    NaN
49983    NaN
49985    NaN
49986     no
49987     no
49988     no
49989    yes
49990     no
49991    NaN
49992     no
49993    NaN
49994     no
49995     no
49996     no
49997     no
49998     no
49999     no
Name: unrepaired_damage, Length: 48056, dtype: object

We have just a couple things left to clean. Recall earlier that we noticed the "postal_code" column is formatted as an int and thus displaying summary stats, which is misleading. Let's convert to a string to prevent that:

In [47]:
autos.loc[:,["postal_code"]] = autos.postal_code.astype(str)
autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48056 entries, 0 to 49999
Data columns (total 17 columns):
date_crawled          48056 non-null int64
name                  48056 non-null object
price                 48056 non-null int64
ab_test               48056 non-null object
vehicle_type          39265 non-null object
registration_year     46179 non-null float64
gearbox               45728 non-null object
power_ps              43059 non-null float64
model                 45630 non-null object
odometer_km           48056 non-null int64
registration_month    43586 non-null float64
fuel_type             44047 non-null object
brand                 48056 non-null object
unrepaired_damage     38985 non-null object
ad_created            48056 non-null int64
postal_code           48056 non-null object
last_seen             48056 non-null int64
dtypes: float64(3), int64(5), object(9)
memory usage: 7.8+ MB

Finally, at the outset we noted five columns with missing (null) values: "vehicle_type", "gearbox", "model", "fuel_type", and "unrepaired_damage". We need to decide how best to handle these columns.

Let's go back to the original questions we set out to answer with this data:

1. What is the average price for each car brand? Which brands are most and least expensive?
2. What is the average mileage for each brand? Does it correlate to price?
3. What are the most common brand/model combinations?
4. How does reported damage influence price?

We can see that the only columns that relate to our questions are "model" and "unrepaired_damage". We'll leave the other columns as is and explore these further.

Above we can see that "model" info is missing for about 2,500 entries, which is a fairly small precentage of our overall data. We can see that one of the questions we intend to answer is the most common brand/model combo, so all entries we look at much have info for both these columns. Since that's the case, we can feel comfortable removing these entires:

In [48]:
autos = autos.loc[autos.model.notna()]
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,20160326,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004.0,manual,158.0,andere,150000,3.0,lpg,peugeot,no,20160326,79588,20160406
1,20160404,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997.0,automatic,286.0,7er,150000,6.0,benzin,bmw,no,20160404,71034,20160406
2,20160326,Volkswagen_Golf_1.6_United,8990,test,limousine,2009.0,manual,102.0,golf,70000,7.0,benzin,volkswagen,no,20160326,35394,20160406
3,20160312,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,small car,2007.0,automatic,71.0,fortwo,70000,6.0,benzin,smart,no,20160312,33729,20160315
4,20160401,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,station_wagon,2003.0,manual,NaN,focus,150000,7.0,benzin,ford,no,20160401,39218,20160401
5,20160321,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006.0,automatic,150.0,voyager,150000,4.0,diesel,chrysler,NaN,20160321,22962,20160406
6,20160320,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995.0,manual,90.0,golf,150000,8.0,benzin,volkswagen,NaN,20160320,31535,20160323
7,20160316,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998.0,manual,90.0,golf,150000,12.0,diesel,volkswagen,no,20160316,53474,20160407
8,20160322,Seat_Arosa,250,test,NaN,2000.0,manual,NaN,arosa,150000,10.0,NaN,seat,no,20160322,7426,20160326
9,20160316,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997.0,manual,90.0,megane,150000,7.0,benzin,renault,no,20160316,15749,20160406
12,20160331,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,small car,2010.0,automatic,71.0,fortwo,50000,9.0,benzin,smart,no,20160331,34590,20160406
13,20160323,Audi_A3_1.6_tuning,1350,control,limousine,1999.0,manual,101.0,a3,150000,11.0,benzin,audi,no,20160323,12043,20160401
14,20160323,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,small car,2007.0,manual,75.0,clio,150000,9.0,benzin,renault,NaN,20160323,81737,20160401
16,20160316,Opel_Vectra_B_Kombi,350,test,station_wagon,1999.0,manual,101.0,vectra,150000,5.0,benzin,opel,no,20160316,57299,20160318
17,20160329,Volkswagen_Scirocco_2_G60,5500,test,NaN,1990.0,manual,205.0,scirocco,150000,6.0,benzin,volkswagen,no,20160329,74821,20160405
18,20160326,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995.0,manual,150.0,3er,150000,NaN,benzin,bmw,NaN,20160326,54329,20160402
19,20160317,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,NaN,2004.0,manual,124.0,andere,150000,2.0,lpg,mazda,no,20160317,40878,20160317
20,20160305,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,station_wagon,2003.0,manual,131.0,a4,150000,5.0,diesel,audi,NaN,20160305,53913,20160307
22,20160328,MINI_Cooper_S_Cabrio,25450,control,convertible,2015.0,manual,184.0,cooper,10000,1.0,benzin,mini,no,20160328,44789,20160401
26,20160403,Volkswagen_Polo_Fox,777,control,small car,1992.0,manual,54.0,polo,125000,2.0,benzin,volkswagen,no,20160403,38110,20160405
28,20160319,MINI_Cooper_D,5250,control,small car,2007.0,manual,110.0,cooper,150000,7.0,diesel,mini,yes,20160319,15745,20160407
29,20160402,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,station_wagon,2004.0,automatic,204.0,e_klasse,150000,10.0,diesel,mercedes_benz,no,20160402,47638,20160402
30,20160314,Peugeot_206_Unfallfahrzeug,80,test,small car,2002.0,manual,60.0,2_reihe,150000,6.0,benzin,peugeot,yes,20160314,57076,20160314
31,20160314,Noch_gut_erhaltenen_C_320,2850,test,station_wagon,2002.0,automatic,218.0,c_klasse,150000,7.0,benzin,mercedes_benz,no,20160314,41065,20160316
32,20160320,Corsa_mit_TÃœV_5.2016,350,control,small car,1999.0,manual,NaN,corsa,150000,7.0,benzin,opel,NaN,20160320,27619,20160406
33,20160315,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,4800,test,station_wagon,2006.0,manual,140.0,a3,150000,8.0,diesel,audi,no,20160315,61169,20160407
34,20160405,Bmw_530d__navi_tuv03/18,2600,test,station_wagon,2000.0,automatic,193.0,5er,150000,6.0,diesel,bmw,NaN,20160405,95111,20160407
35,20160329,Ford_Mondeo,1200,test,station_wagon,1998.0,manual,NaN,mondeo,150000,12.0,benzin,ford,no,20160329,52428,20160406
36,20160316,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,7500,test,station_wagon,2007.0,manual,131.0,mondeo,150000,11.0,diesel,ford,no,20160316,34246,20160405
37,20160323,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,13800,test,bus,2012.0,manual,140.0,altea,90000,2.0,diesel,seat,no,20160323,85113,20160405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49966,20160402,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,1490,control,small car,2006.0,manual,68.0,c1,150000,7.0,benzin,citroen,yes,20160402,26603,20160402
49967,20160312,VW_Passat_2_0_TDI_comfortline,4999,test,station_wagon,2006.0,manual,140.0,passat,150000,5.0,diesel,volkswagen,NaN,20160312,70619,20160317
49968,20160401,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986.0,automatic,90.0,andere,150000,9.0,diesel,mercedes_benz,no,20160401,40227,20160405
49969,20160317,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,NaN,2005.0,manual,136.0,x_trail,150000,5.0,diesel,nissan,no,20160317,17379,20160325
49970,20160321,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010.0,automatic,136.0,c4,60000,4.0,diesel,citroen,no,20160321,14947,20160407
49971,20160329,W.Lupo_1.0,950,test,small car,2001.0,manual,50.0,lupo,150000,4.0,benzin,volkswagen,no,20160329,65197,20160329
49972,20160326,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004.0,automatic,150.0,vito,150000,10.0,diesel,mercedes_benz,yes,20160326,65326,20160328
49973,20160327,Mercedes_Benz_SLK_200_Kompressor,6000,control,convertible,2004.0,manual,163.0,slk,150000,11.0,benzin,mercedes_benz,no,20160327,53567,20160327
49975,20160327,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,small car,2012.0,automatic,88.0,jazz,100000,11.0,hybrid,honda,no,20160327,84385,20160405
49976,20160319,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,station_wagon,1992.0,automatic,150.0,80,150000,12.0,benzin,audi,no,20160319,36100,20160407
49977,20160331,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003.0,manual,116.0,c_klasse,150000,2.0,diesel,mercedes_benz,no,20160331,33739,20160406
49978,20160404,Mercedes_Benz_E_200_Classic,900,control,limousine,1996.0,automatic,136.0,e_klasse,150000,9.0,benzin,mercedes_benz,yes,20160404,24405,20160406
49979,20160320,Volkswagen_Polo_1.6_TDI_Style,11000,test,small car,2011.0,manual,90.0,polo,70000,11.0,diesel,volkswagen,no,20160320,48455,20160407
49980,20160312,Ford_Escort_Turnier_16V,400,control,station_wagon,1995.0,manual,105.0,escort,125000,3.0,benzin,ford,NaN,20160312,56218,20160406
49981,20160315,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,station_wagon,1998.0,manual,115.0,astra,150000,12.0,benzin,opel,no,20160315,86859,20160405
49982,20160329,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,small car,2004.0,manual,NaN,fabia,90000,7.0,benzin,skoda,NaN,20160329,45884,20160329
49983,20160306,Ford_focus_99,600,test,small car,1999.0,manual,101.0,focus,150000,4.0,benzin,ford,NaN,20160306,52477,20160309
49986,20160404,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010.0,automatic,218.0,300c,125000,11.0,diesel,chrysler,no,20160404,73527,20160406
49987,20160322,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013.0,manual,150.0,a3,50000,11.0,diesel,audi,no,20160322,94362,20160326
49988,20160328,BMW_330_Ci,9550,control,NaN,2001.0,manual,231.0,3er,150000,10.0,benzin,bmw,no,20160328,83646,20160407
49989,20160311,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,small car,1997.0,manual,NaN,polo,150000,5.0,benzin,volkswagen,yes,20160311,21244,20160312
49990,20160321,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012.0,manual,156.0,a_klasse,30000,12.0,benzin,mercedes_benz,no,20160321,58239,20160406
49991,20160306,Kleinwagen,500,control,NaN,2016.0,manual,NaN,twingo,150000,NaN,benzin,renault,NaN,20160306,61350,20160306
49992,20160310,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,small car,2009.0,manual,120.0,andere,125000,9.0,lpg,fiat,no,20160310,68642,20160313
49994,20160322,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,station_wagon,2001.0,automatic,299.0,a6,150000,1.0,benzin,audi,no,20160322,46537,20160406
49995,20160327,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011.0,automatic,239.0,q5,100000,1.0,diesel,audi,no,20160327,82131,20160401
49996,20160328,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,convertible,1996.0,manual,75.0,astra,150000,5.0,benzin,opel,no,20160328,44807,20160402
49997,20160402,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,convertible,2014.0,automatic,69.0,500,5000,11.0,benzin,fiat,no,20160402,73430,20160404
49998,20160308,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,station_wagon,2013.0,manual,150.0,a3,40000,11.0,diesel,audi,no,20160308,35683,20160405
49999,20160314,Opel_Vectra_1.6_16V,1250,control,limousine,1996.0,manual,101.0,vectra,150000,1.0,benzin,opel,no,20160313,45897,20160406

Now let's see how many null values exists for the unrepaired damage column:

In [49]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45630 entries, 0 to 49999
Data columns (total 17 columns):
date_crawled          45630 non-null int64
name                  45630 non-null object
price                 45630 non-null int64
ab_test               45630 non-null object
vehicle_type          37823 non-null object
registration_year     44018 non-null float64
gearbox               43706 non-null object
power_ps              41293 non-null float64
model                 45630 non-null object
odometer_km           45630 non-null int64
registration_month    41878 non-null float64
fuel_type             42426 non-null object
brand                 45630 non-null object
unrepaired_damage     37589 non-null object
ad_created            45630 non-null int64
postal_code           45630 non-null object
last_seen             45630 non-null int64
dtypes: float64(3), int64(5), object(9)
memory usage: 6.3+ MB

Roughly 18% of remaining entries have a null value for unrepaired_damage. That's quite a bit of data loss, so perhaps we're best to leave those rows intact and just analyze the data for which we have damage information collected.

### Analyzing Our Cleaned Data

Now that we've prepared a cleaner version of our original data set, let's start answering some of the initial questions we had. Most of those questions pertain to "brand" info, so let's start there. We wanted to know the average price of each of the top 10 brands. Here are the top 10 brands in terms of listing frequency:

In [50]:
top_brands = autos.brand.value_counts().iloc[:10]
top_brands

volkswagen       9875
opel             5064
bmw              4967
mercedes_benz    4411
audi             3933
ford             3228
renault          2240
peugeot          1327
fiat             1198
seat              889
Name: brand, dtype: int64

Next we'll iterate over this list to calculate the mean price of each brand:

In [51]:
price_dict = {}
for brand in top_brands.index:
    mean_price = autos.loc[autos.brand == brand,['price']]['price'].mean()
    price_dict[brand] = mean_price
price_dict_items = price_dict.items() # translating dict to list of tuples so we can sort
price_dict_sorted = sorted(price_dict_items, key=lambda kv: kv[1], reverse=True) # sorting on second tuple value (mean)
brand_table = pd.DataFrame(price_dict_sorted, columns=["brand", "mean_price"]) # translating back to dataframe for easier reading
brand_table = brand_table.set_index("brand")
brand_table["brand_counts"] = top_brands
brand_table.index.name = None
brand_table

                mean_price  brand_counts
audi           8412.918637          3933
bmw            7852.724381          4967
mercedes_benz  7734.425527          4411
volkswagen     5325.422177          9875
seat           4395.188976           889
ford           3620.337361          3228
peugeot        3162.447626          1327
opel           2969.628555          5064
fiat           2836.639399          1198
renault        2415.731250          2240

We can see that Audi has the highest average price, followed closely by BMW and Mercedes. Then there is a sizeable drop to Volkswagen, which is the brand with the greatest number of listings and appears to dominate the mid-price market. The least expensive brands are Opel, Fiat and Renault. Interesting to note, though, that Opel is the second most listed brand in our data, suggesting that it dominates the low-price market.

Next we'll calculate mean mileage for our top brands and add it to our dataframe that alread contains brand names and mean price info:

In [52]:
mileage_dict = {}
for brand in top_brands.index:
    mean_mileage = autos.loc[autos.brand == brand,['odometer_km']]['odometer_km'].mean()
    mileage_dict[brand] = mean_mileage
mileage_items = pd.Series(mileage_dict)
brand_table["mean_mileage"] = mileage_items
brand_table = brand_table.reindex(columns=["brand_counts", "mean_price", "mean_mileage"]) #reordering our columns for easier reading
brand_table = brand_table.sort_values(by="mean_mileage", ascending=False)
brand_table

               brand_counts   mean_price   mean_mileage
bmw                    4967  7852.724381  133497.080733
mercedes_benz          4411  7734.425527  132226.252550
audi                   3933  8412.918637  131493.770659
opel                   5064  2969.628555  129299.960506
volkswagen             9875  5325.422177  128915.949367
renault                2240  2415.731250  128223.214286
peugeot                1327  3162.447626  126996.985682
ford                   3228  3620.337361  124307.620818
seat                    889  4395.188976  121642.294713
fiat                   1198  2836.639399  117399.833055

What's really interesting here is that there does appear to be a correlation between average mileage and average price, but it's the inverse of what one might expect. Our more expensive brands - BMW, Mercedes, Audi - have the highest average mileage, suggesting owners of these brands hold on to their vehicles longer and the brands themselves hold their value well. Conversely, low-price brands have the lowest average mileage, suggesting these cars lose value quickly, possibly due to inferior craftsmanship (hence the lower price).

Next we'll look at the most common brand/model combinations:

In [53]:
new_table = pd.DataFrame()
for item in top_brands.index:
    model_count = autos.loc[autos.brand == item, ["model"]]["model"].value_counts()
    model_count = pd.DataFrame(model_count)
    model_count.reset_index(level=0, inplace=True)
    model_count.rename(columns={'index':'model', 'model':'count'}, inplace=True)
    model_count["brand"] = item
    new_table = pd.concat([new_table, model_count], ignore_index=True)
    
new_table = new_table[['brand', 'model', 'count']]
new_table = new_table.sort_values('count', ascending=False)
new_table

             brand        model  count
0       volkswagen         golf   3898
38             bmw          3er   2682
1       volkswagen         polo   1688
22            opel        corsa   1680
23            opel        astra   1410
2       volkswagen       passat   1382
66            audi           a4   1249
48   mercedes_benz     c_klasse   1155
39             bmw          5er   1142
49   mercedes_benz     e_klasse    966
67            audi           a3    864
68            audi           a6    801
82            ford        focus    792
83            ford       fiesta    752
3       volkswagen  transporter    669
96         renault       twingo    654
106        peugeot      2_reihe    610
50   mercedes_benz     a_klasse    584
24            opel       vectra    558
40             bmw          1er    532
97         renault         clio    497
84            ford       mondeo    486
4       volkswagen       touran    463
112           fiat        punto    441
51   mercedes_benz       andere    419
25            opel       zafira    418
85            ford           ka    362
122           seat        ibiza    349
5       volkswagen         lupo    342
98         renault       megane    342
..             ...          ...    ...
128           seat     alhambra     41
93            ford         kuga     41
18      volkswagen        jetta     38
61   mercedes_benz           cl     38
78            audi           q7     38
94            ford       fusion     33
45             bmw      m_reihe     32
44             bmw       andere     32
104        renault        modus     31
19      volkswagen      phaeton     30
46             bmw          6er     30
62   mercedes_benz          glk     27
129           seat       andere     27
36            opel      calibra     25
79            audi           q3     25
63   mercedes_benz     g_klasse     24
64   mercedes_benz     v_klasse     22
37            opel       antara     21
20      volkswagen           cc     20
111        peugeot      5_reihe     14
130           seat          mii     10
105        renault          r19      9
80            audi           90      8
21      volkswagen       amarok      7
65   mercedes_benz           gl      7
131           seat         exeo      7
121           fiat        croma      5
95            ford        b_max      1
81            audi          200      1
47             bmw           i3      1

[132 rows x 3 columns]

Keep in mind we've limited our analysis here to just our top 10 brands. Among those, we can see that the Volkswagen Golf is the most popular car. In fact, Volkswagen has three cars in the top 10 with the Volkswagen Polo and Volkswagen Passat coming in at #3 and #6 respectively. We can see that Mercedez, BMW and Opel are also well represented in the top 10, each having two cars that ranked.

Finally, let's try to see what impact reported damage has on a car. First we'll calculate the mean price of cars with reported damage:

In [59]:
autos.loc[autos.unrepaired_damage == 'yes',['price']].price.mean()

2192.9995448338645

Now we'll compare that to cars with no reported damage:

In [60]:
autos.loc[autos.unrepaired_damage == 'no',['price']].price.mean()

6409.719837324898

We can see a clear trend from these numbers - cars with no reported damage are listed for roughly 3X more on average than cars with no damage.

### Conclusions

The focus of this exercise was to clean and prepare a scraped dataset for analysis. In the process we had to make some decisions regarding which rows to keep and which to scrap. In the end we only removed about 4,000 rows, or ~8% of our data. We preserved rows where the problematic data wouldn't factor into our analysis. We also fixed a number of issues with data formatting.

Our analysis showed that Audi, BMW and Mercedez appear to dominate the premium market, holding the highest average pricing by brand. Conversely, Volkswagen alone dominates the mid-range market, while Opel, Fiat and Renault are in control of the low-price market.

We also saw an interesting trend when looking at the correlation between average price and average mileage. Surprisingly, the highest priced vehicles had the highest average mileage, suggesting that premium brand owners are waiting longer to sell their vehicles, which retain value much better than lower-cost brands.

Finally we saw that reported damage appears to have a significant impact on value, with those vehicles selling for 3X less on average.